_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 64
device:
    value: cuda
epochs:
    value: 10
image_size:
    value: 28
lr:
    value: 0.0003
run_name:
    value: DDPM_MNIST
